#!/bin/sh
#
# Copyright (c) Pierre Habouzit, 2007
#

USAGE="[-c] [<target_dir>]"
if [ -z "$GUILT_VERSION" ]; then
	echo "Invoking `basename "$0"` directly is no longer supported." >&2
	exit 1
fi

_main() {

case $# in
    0)
	usage
	;;
    1)
	if [ "$1" = "-c" ]; then
	    usage
	else
	    target_dir=${1:-"patches"}
	fi
	;;
    2)
	[ "$1" != "-c" ] && usage
	target_dir=${2:-"patches"}
	if [ -e "$target_dir" ]; then
	    rm $target_dir/*
	fi
	bottom=refs/patches/$branch/`head -1 $applied`
	git format-patch -s ${bottom}^..HEAD -o $target_dir > /dev/null
	git diff > $target_dir/9999-uncommitted.patch
	return $?
	;;
esac

if [ -e "$target_dir" ]; then
	die "Specified directory already exists"
fi

trap "rm -rf \"$target_dir\"" 0
mkdir -p "$target_dir"

get_full_series | tee "$target_dir/series" | while read p; do
	silent mkdir -p "`dirname $target_dir/$p`" || true
	cp "$GUILT_DIR/$branch/$p" "$target_dir/$p"
done

trap - 0
disp "Series exported to \"$target_dir\" sucessfully."

}
